version: '2'
services:
  php-app:
    build: .
    volumes:
      - .:/app
      - /app/vendor/
    environment:
      - DATABASE_URL=postgres://todoapp@postgres/todos
    depends_on:
      - postgres
    ports:
      - 9000:9000
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      - POSTGRES_USER=todoapp
      - POSTGRES_DB=todos
    restart: always
    
  nginx:
    image: nginx:1.11.10-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 3000:80
    restart: always
